apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: fintech-kafka
spec:
  kafka:
    version: 4.1.1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      process.roles: broker,controller
      node.id: 0
      controller.listener.names: CONTROLLER
      listeners: PLAINTEXT://:9092,CONTROLLER://:9093
      inter.broker.listener.name: PLAINTEXT
      controller.quorum.voters: 0@fintech-kafka-controller-0.fintech-kafka-controller.fintech.svc:9093
  entityOperator:
    topicOperator: {}
    userOperator: {}
